# Generated by Django 5.2.5 on 2025-08-28 10:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(help_text='Unique equipment identifier (e.g., EQX1001)', max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Excavator', 'Excavator'), ('Crane', 'Crane'), ('Bulldozer', 'Bulldozer'), ('Grader', 'Grader'), ('Loader', 'Loader'), ('Compactor', 'Compactor'), ('Dump Truck', 'Dump Truck')], max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=50)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Engine', 'Engine'), ('Hydraulics', 'Hydraulics'), ('Transmission', 'Transmission'), ('Fuel System', 'Fuel System'), ('Cooling System', 'Cooling System'), ('Electrical', 'Electrical'), ('Brakes', 'Brakes'), ('MISC', 'MISC')], max_length=50)),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Warning', 'Warning'), ('Critical', 'Critical'), ('Maintenance Required', 'Maintenance Required')], default='Good', max_length=50)),
                ('engine_temperature', models.FloatField(blank=True, help_text='Engine temperature in Celsius', null=True)),
                ('oil_pressure', models.FloatField(blank=True, help_text='Oil pressure in PSI', null=True)),
                ('fuel_level', models.FloatField(blank=True, help_text='Fuel level percentage', null=True)),
                ('fuel_consumption_rate', models.FloatField(blank=True, help_text='Fuel consumption rate L/hr', null=True)),
                ('battery_voltage', models.FloatField(blank=True, help_text='Battery voltage', null=True)),
                ('alert_message', models.TextField(blank=True, help_text='Alert description', null=True)),
                ('severity', models.IntegerField(default=1, help_text='Severity level 1-5')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='catrentapp.machine')),
            ],
            options={
                'verbose_name': 'Equipment Health Record',
                'verbose_name_plural': 'Equipment Health Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('operator_id', models.CharField(help_text='Operator/User ID', max_length=100)),
                ('operator_name', models.CharField(default='Unknown', max_length=200)),
                ('site_id', models.CharField(help_text='Site where equipment is deployed', max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expected_end_date', models.DateTimeField()),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Active', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='catrentapp.machine')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=200, null=True)),
                ('operator_id', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('engine_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Engine runtime hours for the day', max_digits=8)),
                ('idle_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Idle hours for the day', max_digits=8)),
                ('fuel_consumed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fuel consumed in liters', max_digits=8)),
                ('distance_traveled', models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in kilometers', max_digits=8)),
                ('productivity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Daily productivity score (0-100)', max_digits=5)),
                ('work_type', models.CharField(blank=True, help_text='Type of work performed', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='catrentapp.machine')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='catrentapp.rental')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('machine', 'date')},
            },
        ),
    ]
