# Generated by Django 4.2.1 on 2025-08-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='catrentapp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=100)),
                ('week', models.IntegerField()),
                ('checkout_date', models.DateField()),
                ('checkin_date', models.DateField()),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_count', models.IntegerField()),
                ('engine_hours', models.IntegerField()),
                ('idle_hours', models.IntegerField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='catrentapp.machine')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('Engine', 'Engine'), ('Fuel', 'Fuel'), ('Drive', 'Drive'), ('MISC', 'MISC')], max_length=50)),
                ('air_filter_pressure', models.FloatField(blank=True, null=True)),
                ('exhaust_gas_temperature', models.FloatField(blank=True, null=True)),
                ('hydrolic_pump_rate', models.FloatField(blank=True, null=True)),
                ('oil_pressure', models.FloatField(blank=True, null=True)),
                ('padel_sensor', models.FloatField(blank=True, null=True)),
                ('system_voltage', models.FloatField(blank=True, null=True)),
                ('water_in_fuel', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('brake_control', models.FloatField(blank=True, null=True)),
                ('transmission_pressure', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='catrentapp.machine')),
            ],
        ),
    ]
