# Generated by Django 5.2.5 on 2025-08-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='type',
            field=models.CharField(choices=[('Excavator', 'Excavator'), ('Crane', 'Crane'), ('Bulldozer', 'Bulldozer'), ('Loader', 'Loader')], max_length=100),
        ),
    ]
