# Generated by Django 5.2.5 on 2025-08-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0002_alter_machine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='checkout_count_t_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='checkout_count_t_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='engine_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='engine_hours_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='engine_hours_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='equipment_type_encoded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='idle_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='idle_ratio_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='maintenance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='maintenance_per_day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='month_cos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='month_sin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='pct_maint',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='price_index',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='rate_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='rate_relative',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='recent_maintenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='rolling_max_4w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rolling_mean_4w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rolling_std_4w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='target_checkout_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='usage_efficiency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='week',
            field=models.CharField(default='2025-W34', help_text='Year-week (e.g., 2025-W35)', max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='week_cos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rental',
            name='week_sin',
            field=models.FloatField(default=0.0),
        ),
    ]
