# Generated by Django 5.2.5 on 2025-08-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catrentapp', '0003_rental_checkout_count_t_1_rental_checkout_count_t_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
